plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "io.freefair.lombok" version "9.5.0"
	id "com.modrinth.minotaur" version "2.9.0"
}

group = project.maven_group

loom {
    accessWidenerPath = file("src/main/resources/radialmacros.accesswidener")
}

repositories {
	mavenCentral()

	maven { url "https://maven.terraformersmc.com/releases/" }
	maven { url "https://repo.eclipse.org/content/groups/releases/" }
	maven { url "https://jitpack.io" }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation ("com.terraformersmc:modmenu:${project.modmenu_version}") {
		exclude (group: "net.fabricmc.fabric-api")
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	archiveFileName = "RadialMacros-${project.version}.jar"
	
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

modrinth {
	token = System.getenv("MODRINTH_TOKEN")
	projectId = "1Y1WxYnm"
	versionNumber = project.version
	uploadFile = jar
	gameVersions = ["${minecraft_version}"]
	loaders = ["fabric"]
	uploadFile = "./build/libs/RadialMacros-${project.version}.jar"
	dependencies {
		required.project "fabric-api"
		optional.project "modmenu"
	}
}
